### PR TITLE
Add a skip about CRD domains

### PR DESCRIPTION
**Pull request by calebschoepp**
See [here](https://github.com/spinkube/spin-operator/pull/271) for a draft of what this change looks like.

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]
I'm in support of this change. This does make a point that SpinKube sub-projects must all operate under the guise of SpinKube, rather than the other way around. This also ensures that sub-projects can evolve and/or be renamed without having to break apps running in userspace (Kubernetes).

**Review by Mossaka — APPROVED** [review]

**Comment by calebschoepp** [comment]
I'm looking for an approval from the main SpinKube projects before merging to make sure we have consensus. Tagging the appropriate people to try and get the approvals so we can move this forward.

Runtime Class Manager Maintainers: @flavio OR  @voigt OR @0xE282B0 could you please take a look.

**Comment by bacongobbler** [comment]
One quick thought here: we don't have documentation anywhere that describes how to upgrade from one version of spin-operator to the next, correct? If so we'd probably want to call out the breaking change in those docs.

I _think_ the docs only talk about how to bootstrap a cluster from scratch, so we don't have to worry too much about upgrade paths, but worth keeping in mind.

**Review by devigned — APPROVED** [review]
I approve of this proposal and believe that the early we can do this the better. It will be a breaking change, but it will be less impactful the sooner we do it.

**Comment by calebschoepp** [comment]
In a SpinKube community meeting we had expressed the desire to have approval from each sub-project. The main approval missing is from the runtime-class-manager.

@flavio @0xE282B0 @voigt I'll give y'all to the end of the week to comment and otherwise I'll assume that you have no strong opinions here and I'll go forward with merging this skip.

**Review by michelleN — APPROVED** [review]

**Pull request merged**
